FROM docker.io/oven/bun:1-debian AS build
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install
COPY . .
RUN bunx prisma generate

FROM docker.io/oven/bun:1-slim
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --production
COPY --from=build /app/prisma/generated ./prisma/generated
COPY . .
EXPOSE 3000
CMD ["bun", "run", "start"]
